### ISSUE TITLE
Webpack 5's "getOptions" is missing

### ISSUE THREAD

**Issue by ef4** [webpack-contrib/thread-loader#106]
### Expected Behavior

Loaders that use webpack 5's `this.getOptions()` API should work with thread-loader.

See https://github.com/webpack/webpack/pull/10017

### Actual Behavior

`this.getOptions` is undefined.

### How Do We Reproduce?

Pick any loader that uses `getOptions` from `loader-utils` and modify it to use `this.getOptions` instead. That works when using webpack 5 without thread-loader, but fails when used behind thread-loader.

**Comment by alexander-akait** [comment]
PR welcome

**Comment by irfan-maulana-tkp** [comment]
Adding the Docs: https://webpack.js.org/migrate/5/#getoptions-method-for-loaders

**Comment by ccabrales** [comment]
Anybody know how to go about fixing this?

**Comment by alexander-akait** [comment]
@qnighy Can you help with this, because we need fix compatibility with webpack v5 before release

**Comment by qnighy** [comment]
@alexander-akait sure, I'll try to reproduce and fix it this weekend.

**Comment by qnighy** [comment]
Reproduction: https://github.com/qnighy/thread-loader-issue-106

**Comment by qnighy** [comment]
It also reproduces with `sass-loader@11` so I'm going to update the devDependency in thread-loader and fix the test failure.

**Comment by qnighy** [comment]
Created a fix https://github.com/webpack-contrib/thread-loader/pull/113 though it's not an optimal solution.
