### ISSUE TITLE
`LoaderContext.mode` is missing when run by `thread-loader`

### ISSUE THREAD

**Issue by yyx990803** [webpack-contrib/thread-loader#123]
- Operating System: macOS 11.4
- Node Version: v16.3.0
- NPM Version: 7.15.1
- webpack Version: 4.46.0 / 5.45.1
- thread-loader Version: 3.0.4

### Expected Behavior

`this.mode` in a loader is consistent when running with or without `thread-loader`

### Actual Behavior

`this.mode` is always `undefined` when running inside `thread-loader`

### How Do We Reproduce?

https://github.com/yyx990803/thread-loader-bug

**Comment by alexander-akait** [comment]
PR welcome :+1:
