### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: loaderContext.getLogger is not a function

### ISSUE THREAD

**Issue by yxw007** [webpack-contrib/thread-loader#135]
- Operating System: win10
- Node Version: v14.14.0
- NPM Version: 6.14.8
- webpack Version: 5.68.0
- thread-loader Version: 3.0.4

### Expected Behavior

Normal use thread-loader 

### Actual Behavior

![image](https://user-images.githubusercontent.com/9338717/154421065-0ed69a62-6571-4541-967b-939808fa1ea0.png)

### Code

[webpack.config.js](https://github.com/yxw007/webpack-thread-loader-test/blob/master/build/webpack.config.js)

### How Do We Reproduce?

[Mini Produce Environment](https://github.com/yxw007/webpack-thread-loader-test)

### I found a clue
Worker.loaders context is missing some fields and Funtion
![](https://cdn.jsdelivr.net/gh/yxw007/BlogPicBed@master//img/20220217151134.jpg)

The red box shows the missing content, context lack getLoger Function, Therefore, sass failed to obtain the getLog error

![sass-loader/dist/utils.js](https://cdn.jsdelivr.net/gh/yxw007/BlogPicBed@master//img/20220217150405.jpg)

**Comment by AprilArcus** [comment]
see https://github.com/webpack-contrib/sass-loader/issues/1016

**Comment by yxw007** [comment]
> @yxw007 解决了吗，我遇到同样的问题了

版本问题，找一个以前可用的版本吧

**Comment by JX-Zhuang** [comment]
> 

你用的哪个版本

**Comment by JX-Zhuang** [comment]
> > @yxw007 解决了吗，我遇到同样的问题了
> 
> 版本问题，找一个以前可用的版本吧

你用的哪个版本可以解决

**Comment by yxw007** [comment]
> 记得好像是webpack5.x把API都改了导致不能用，但是我直接没有这个插件了，好像要退回至webpack4.x的版本来使用这个插件，那样的话没多大必要了。如果项目不复杂可考虑之前迁移至vite打包，开发幸福指数立马提升。这个插件用的人也不多了，也不维护了建议直接放弃转用vite打包构建吧
