### ISSUE TITLE
webpack 4 Support

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/thread-loader#14]
<h2 align="center"><a href="https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202">Official Migration Guide for Loaders/Plugins</a></h2>

### TODO

- [x] remove usages of `this.options.context` for  `this.rootContext` (https://github.com/webpack-contrib/thread-loader/blob/master/src/index.js#L21). `webpack >= v4.0.0` removed `this.options` from the Loader API and `this.options.context` is now exposed  as `this.rootContext`, which needs to be **added** to current implementation for `webpack` 4 support

 ~~- [x] update usage of `fileDependencies` && `contextDependencies` to reflect new data types. These are `{Set}`'s now instead of an `{Array}` (https://github.com/webpack-contrib/thread-loader/blob/master/src/index.js#L24-L25)~~

### First Contributors

 💁 If you're stuck or in doubt about something always feel free to ask question in the issue thread and/or by pinning one of the @webpack-contrib/org-maintainers

**Comment by iansu** [comment]
Hi, I'm interested in doing this.

**Comment by michael-ciniawsky** [comment]
Feel free to open a PR anytime the it's roughly 'done'  I'm not 💯 if the issue includes everything, but we can triage the rest in the PR :)

**Comment by iansu** [comment]
Sounds good. 👍

**Comment by iansu** [comment]
Is there a contributing guide somewhere? I'm also looking for instructions on how to test this loader or loaders in general.

**Comment by michael-ciniawsky** [comment]
There is no guide atm. `@webpack-contrib/test-utils` (simple webpack wrapper with testing defaults, so one can focus on the tests) is the 'standard' approach for testing `loaders/plugins` an example can be found [here (test structure)](https://github.com/webpack-contrib/html-loader/blob/next/test/loader.test.js)) && [here (test)](https://github.com/webpack-contrib/html-loader/blob/next/test/loader.test.js). It might be necessary to update things here and there in `@webpack-contrib/test-utils` as the package isn't  💯 ready for prime time yet imho. It's best you open a separate PR for adding tests, starting with one 'simple'  test and I promise to help out where needed. Once the loader works locally with `webpack >= v4.0.0` it's totally ok in the current context since providing test(s) is normally our duty in the first place :)

**Comment by iansu** [comment]
Okay, I will look into those. As far as the changes here, I've updated `this.options.context` to use `this.rootContext`. Do we need to do anything to make it backwards compatible with older versions of webpack?

For the second change, I don't think there's anything required there. Both `Array` and `Set` have `forEach` methods that work similarly.

**Comment by michael-ciniawsky** [comment]
> Okay, I will look into those. As far as the changes here, I've updated this.options.context to use this.rootContext. Do we need to do anything to make it backwards compatible with older versions of webpack?

`const context = this.rootContext || this.options.context` should be fine 

> For the second change, I don't think there's anything required there. Both Array and Set have forEach methods that work similarly.

👍

**Comment by iansu** [comment]
Okay, given all that I think the context changes are the only thing that needs to be done. I haven't got a testing setup yet though. Take a look at the PR and let's take it from there.
