### ISSUE TITLE
Not work with webpack-virtual-modules

### ISSUE THREAD

**Issue by yeild** [webpack-contrib/thread-loader#154]
Please see these issues:
https://github.com/storybookjs/storybook/issues/9515
https://github.com/nuxt-community/storybook/issues/102
https://github.com/storybookjs/storybook/issues/12864
![image](https://user-images.githubusercontent.com/23716085/204741977-aee88999-67b2-490f-a22a-eda8a9b18ca6.png)

seems they try not to use thread-loader, as a workaround.

So is there anyway I can use `thread-loader`  with some other loader that used `webpack-virtual-modules` ?

**Comment by alexander-akait** [comment]
Close in favor - https://github.com/webpack-contrib/thread-loader/issues/94, it is the same
