### ISSUE TITLE
webpack 1 complains thread-loader doesn't return a function

### ISSUE THREAD

**Issue by cspotcode** [webpack-contrib/thread-loader#17]
I'm not sure if you intend to support webpack 1.  When using this loader with webpack 1, I see a warning that `cjs.js` doesn't return a function.  This makes sense; it returns an object with the `pitch` method.

It should be possible for `cjs.js` to return something like this to keep webpack 1 happy:

```
module.exports = function() { throw 'should never be called' }
Object.assign(module.exports, require('./index'));
```

I've been able to implement this workaround myself and everything appears to be working.

**Comment by michael-ciniawsky** [comment]
I'm inclined to say `no`, but in case it's really just the CJS wrapper and the build process being buggy send PR for further triage if you like. For further support and fixing other bugs (especially if clearly related to `webpack v1.0.0` or an outdated `loader`) which may occur, definitely no from my side, but others may (want to) do it

**Comment by cspotcode** [comment]
I think webpack 1 checks if `typeof loader === 'function'` and generates a warning if not.  In the case of "thread-loader", it's never invoked because it pitches every single time.  So this is a warning that doesn't matter.  If "thread-loader" is updated to return a function (even though the function will never be invoked) then everyone's happy.

**Comment by cspotcode** [comment]
I discovered another incompatibility with webpack v1, so I'm closing this.  Thanks for your time.
