### ISSUE TITLE
thread-loader 4.0.1 with ts-loader: Cannot read properties of undefined (reading 'plugins')

### ISSUE THREAD

**Issue by xyx-is** [webpack-contrib/thread-loader#179]
- Operating System: Windows 10 x64
- Node Version: v18.16.0
- NPM Version: 9.6.5
- webpack Version: 5.81.0
- thread-loader Version: 4.0.1 (4.0.0 also), and no errors on 3.0.4
- ts-loader: 9.4.2

### Expected Behavior

Works without errors. If I use thread-loader 3.0.4, there are no errors.

### Actual Behavior

Causes the following error.

```
asset main.bundle.js 2.32 KiB [compared for emit] (name: main)
./src/index.ts 39 bytes [built] [code generated] [1 error]

ERROR in ./src/index.ts
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read properties of undefined (reading 'plugins')
    at PoolWorker.fromErrorObj (C:\...\thread-loader-4-ts-loader-reproduction\node_modules\thread-loader\dist\WorkerPool.js:302:12)
    at C:\...\thread-loader-4-ts-loader-reproduction\node_modules\thread-loader\dist\WorkerPool.js:184:29
    at makeLoaderOptions (C:\...\thread-loader-4-ts-loader-reproduction\node_modules\ts-loader\dist\index.js:159:122)
    at getLoaderOptions (C:\...\thread-loader-4-ts-loader-reproduction\node_modules\ts-loader\dist\index.js:103:21)
    at Object.loader (C:\...\thread-loader-4-ts-loader-reproduction\node_modules\ts-loader\dist\index.js:14:21)

webpack 5.81.0 compiled with 1 error in 259 ms
```

### Code

Rules of [webpack.config.js](https://github.com/xyx-is/thread-loader-4-ts-loader-reproduction/blob/a6d611ab265c69b0a3e479a5ce1c19c69b55c5fa/webpack.config.js):
```js
      rules: [
        {
          test: /\.tsx?$/,
          use: [
            {
              loader: "thread-loader",
            },
            {
              loader: "ts-loader",
              options: { transpileOnly: true, happyPackMode: true },
            },
          ],
        },
      ],
```

### How Do We Reproduce?

Reproduction code: https://github.com/xyx-is/thread-loader-4-ts-loader-reproduction

### Suggestion

I consider this ploblem is related to [this thread-loader diff](https://github.com/webpack-contrib/thread-loader/commit/96ddf8c9c8e31f0f47a2c88ff7b87867339f5ebe#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R22) and [this ts-loader code](https://github.com/TypeStrong/ts-loader/blob/a8f29e372442a9a7d67e014988eb5b277ed84748/src/index.ts#L268). ts-loader assumes if `loaderContext._compiler` is not undefined, the object must have "plugins" key and and array value, while thread-loader 4 only sets "fsStartTime" in `loaderContext._compiler`.

**Comment by alexander-akait** [comment]
Yeah, PR welcome

**Comment by steven-Lee-appier** [comment]
I think making the `plugins` property of `_compiler` to fallback as an empty array is a solution ?

```js
 {
 //.... skip other properties
  _compiler: { fsStartTime: this._compiler.fsStartTime, plugins: this_compiler.plugins || [] }
}
```

**Comment by alexander-akait** [comment]
Should work, can you test it using https://github.com/xyx-is/thread-loader-4-ts-loader-reproduction

**Comment by 1bberto** [comment]
I'm also facing the same issue

**Comment by zhonglin94** [comment]
I met the same problem as well

**Comment by alexander-akait** [comment]
Please update https://github.com/webpack-contrib/thread-loader/releases/tag/v4.0.2
