### ISSUE TITLE
this.getOptions is not a function

### ISSUE THREAD

**Issue by szylmzs** [webpack-contrib/thread-loader#197]
I get error with "this.getOptions is not a function" when using thread-loader, and below is config
```javascript
addWebpackModuleRule(
    {
      test: /\.(js|ts)x?$/i,
      use: [
        {
          loader: require.resolve('thread-loader'),
          options: {
            workers: 2
          }
        },
        {
          loader: require.resolve('babel-loader'),
          options: {
            customize: require.resolve('babel-preset-react-app/webpack-overrides')
          }
        }
      ],
      exclude: /node_modules/
    },
    {
      test: /\.less$/i,
      use: [
        {
          loader: require.resolve('thread-loader'),
          options: {
            workers: 2
          }
        },
        {
          loader: 'less-loader',
          options: { paths: [path.resolve(__dirname, 'node_modules')] }
        }
      ],
      exclude: /node_modules/
    }
  )
```

**Comment by szylmzs** [comment]
resolved with downgrade version to 3, but a new issue occurs, seems that take no effect for babel-loader
![image](https://github.com/webpack-contrib/thread-loader/assets/5236065/56945348-8f6e-4455-a851-68ca42dff5a8)

**Comment by szylmzs** [comment]
I found the reason
thread-loader can not handler files in node_modules and I have mounts of dependencies

**Comment by alexander-akait** [comment]
Please use the issue template, sorry I don't undestand the problem, we have https://github.com/webpack-contrib/thread-loader/blob/master/src/worker.js#L169 and support `this.getOptions()`

**Comment by zjtt** [comment]
bro, I have the same problem, how to solve it.

**Comment by alexander-akait** [comment]
You need to update your webpack to 5 version
