### ISSUE TITLE
handle undefined `this.worker.stdio` correctly

### ISSUE THREAD

**Issue by niieani** [webpack-contrib/thread-loader#2]
Not sure how exactly to reproduce, but I get this half way through a compilation:

```
uncaughtException TypeError: Invalid attempt to destructure non-iterable instance
    at /Users/bazyli.brzoska/Projects/p/node_modules/thread-loader/dist/WorkerPool.js:7:585
    at new PoolWorker (/Users/bazyli.brzoska/Projects/p/node_modules/thread-loader/dist/WorkerPool.js:49:25)
    at WorkerPool.distributeJob (/Users/bazyli.brzoska/Projects/p/node_modules/thread-loader/dist/WorkerPool.js:326:23)
    at /Users/bazyli.brzoska/Projects/p/node_modules/async/queue.js:10:5
    at process (/Users/bazyli.brzoska/Projects/p/node_modules/async/internal/queue.js:165:17)
    at Immediate._onImmediate (/Users/bazyli.brzoska/Projects/p/node_modules/async/internal/setImmediate.js:27:16)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

Using Node 8.2.0-rc.1 and latest versions of both `webpack` (3.1) and `thread-loader`.

**Comment by evilebottnawi** [comment]
@niieani can your provide minimum reproducible test repo?

**Comment by niieani** [comment]
As I said, I don't know how. This happens on a large closed-source project and I do not know why. 
One clue is that it might be somehow connected to STDIO not being properly created for the worker, that's why the destructuring [fails here](https://github.com/webpack-contrib/thread-loader/blob/master/src/WorkerPool.js#L23).

Perhaps it's caused by the kernel exhausting all the named pipes and being unable to open more? No idea. In any case, we should probably protect against that and check if `this.worker.stdio` is properly set before destructuring.

**Comment by evilebottnawi** [comment]
@niieani without test case it is bad practice, because your can have other invalid/incorrect `configuration`, `loader` and/or `plugins`, need clarify why it is happens, before something doing.

**Comment by niieani** [comment]
OK, I've found out when `this.worker.stdio` is `undefined` (and thus not an iterable, as the error states), it is when the kernel hits the limit of open files (`ulimit nofile`). It might be worth adding an if statement there to throw a meaningful message instead of breaking the build with an `uncaughtException`.

**Comment by evilebottnawi** [comment]
@niieani good catch, can your do PR?

**Comment by niieani** [comment]
@evilebottnawi I've made a bug report to Node, perhaps they can address whether it's a bug on their side or just missing documentation for childProcess instance's `stdio`.

Ref: https://github.com/nodejs/node/issues/14166

**Comment by niieani** [comment]
Thanks!
