### ISSUE TITLE
README: Need clarification regarding the first two rules

### ISSUE THREAD

**Issue by nyngwang** [webpack-contrib/thread-loader#207]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [x] Not Sure?

### Please Explain in Detail...

There are some caveats listed in README.md. Specifically, my concern around it is the first rule and the third rule:

> Loaders running in a worker pool are limited. Examples:
> 
> Loaders cannot emit files.
> Loaders cannot use custom loader API (i. e. by plugins).
> Loaders cannot access the webpack options.

### Confusion on Rule 1

Isn't that `babel-loader` also emitting files for webpack eventually? In the example given in the readme, it mentioned that it is expected to work with `babel-loader`. I need some clarifications here as I have some misunderstandings.

### Confusion on Rule 3

In my case, I'm using babel-loader with some custom options like `rootMode: 'upward'`, and in my babel.config.js I also included some third-party plugins like `react-refresh/babel` for HMR with the corresponding plugin in my webpack.config.js. Does this rule mean that `babel-loader` could not access these plugins?

### Your Proposal for Changes

No. I just need some clarification.

**Comment by nyngwang** [comment]
@alexander-akait Could you help? Thank you.

**Comment by nyngwang** [comment]
I tried thread-loader anyway regardless of its correctness as mentioned above. In the end, it increased my time of compilation. I did try warmup and all kinds of combinations with the settings. The results are all the same: slower.

**Comment by alexander-akait** [comment]
Yes, it will be faster only for really big projects, because a creation of threads are very expensive
