### ISSUE TITLE
Incorrect peerDependency for webpack 4.x

### ISSUE THREAD

**Issue by stnwk** [webpack-contrib/thread-loader#21]
When having installed webpack 4.0 and thread-loader 1.1.4, you get the following warning by yarn/npm although webpack 4 is supported?

```
" > thread-loader@1.1.4" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
```

**Comment by evilebottnawi** [comment]
@stnwk Done https://github.com/webpack-contrib/thread-loader/pull/22

**Comment by stnwk** [comment]
Thank you! :)
