### ISSUE TITLE
Get loader context in loader which is run in thread pool

### ISSUE THREAD

**Issue by clarkdo** [webpack-contrib/thread-loader#24]
@sokra 
We are using https://github.com/vuejs/vue-style-loader for loading `.vue` styles and trying to speed css loading up by using `thread-loader`.

But in `vue-style-loader`, it need to access properties in `loader context` like: [target](https://github.com/vuejs/vue-style-loader/blob/master/index.js#L14) and [resourcePath](https://github.com/vuejs/vue-style-loader/blob/master/index.js#L30).

If I understood correctly, `thread-loader` seems to run these loaders in a new context which doesn't include them, is there any way to get the properties ?

**Comment by sokra** [comment]
These properties could be added to the thread loader. Send a PR

**Comment by Schlesiger** [comment]
I have upgraded to Webpack 4 and am attempting to use `thread-loader` with `mini-css-extract-plugin` and believe I am running into the same issue.
