### ISSUE TITLE
Emphasise the need to override poolTimeout when watching

### ISSUE THREAD

**Issue by edmorley** [webpack-contrib/thread-loader#26]
Hi!

As [mentioned here](https://github.com/webpack/webpack/issues/7086#issuecomment-383467496), when watching is enabled (ie the development config with webpack-dev-server) the `poolTimeout` option should be changed from its default of `500` ms to `Infinity` to avoid paying the overhead of worker startup on every rebuild.

This is hinted at in a code comment of the examples section of the docs, however it seems that people aren't noticing this. eg:
https://github.com/facebook/create-react-app/issues/4346
https://github.com/jaredpalmer/razzle/issues/587

As such I think it would make sense to call this out explicitly in the usage section of the docs.

**Comment by evilebottnawi** [comment]
@edmorley PR welcome :+1:

**Comment by jantimon** [comment]
Oh - I wish I would have seen this before.  
I just stumbled into the same problem:


Removing thread-loader [decreased the incremental build duration by over 50%](
https://github.com/namics/webpack-config-plugins/issues/24#issuecomment-448297256) because of the booting phase of the workers.

**Comment by jantimon** [comment]
@edmorley this is fixed with #52 :)

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/thread-loader/pull/52

**Comment by edmorley** [comment]
Many thanks!
