### ISSUE TITLE
Add silent mode for production builds

### ISSUE THREAD

**Issue by vertic4l** [webpack-contrib/thread-loader#28]
I'm analyzing my webpack bundle size actually, and the profiler always adds 2 lines at the beginning of stats.json which are coming from the thread-loader.

Is there a way to make it silent, or could you add an option?

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by vertic4l** [comment]
Nevermind, just realized it's coming from ts-checker-webpack-plugin.
