### ISSUE TITLE
Development dependencies don't compile with Node v10.11

### ISSUE THREAD

**Issue by kevinburke** [webpack-contrib/thread-loader#35]
I get a number of errors while compiling `node-sass` (which depends on "nan") and `fsevents`. Both of these versions are fixed in package-lock.json to an older version of the package.

**Comment by mistic** [comment]
This is solved on https://github.com/webpack-contrib/thread-loader/pull/36

**Comment by mistic** [comment]
@evilebottnawi we can close this issue
