### ISSUE TITLE
Webpack watcher stops after compilation error when using thread loader

### ISSUE THREAD

**Issue by KonstantinSimeonov** [webpack-contrib/thread-loader#5]
When using webpack in watch mode with thread loader, compilation errors seem to stop the watch. For an example, if I make a syntax error and save the file, even if I fix it later and save the file again, webpack won't recompile. This scenario works fines when I remove thread-loader from webpack config.

Here is a [sample project](https://github.com/KonstantinSimeonov/curly-potato) that reproduces the scenario. Steps to reproduce:

1. `yarn && yarn watch`
2. after the watcher has started, introduce a syntax error in either `index.js` or `Header.js` and save the file
3. fix the syntax error and save the file again

I've encountered this issue on two different projects, on two different machines (windows and linux) and on both `node v6.11.2` and `node v8.4.0`.

The versions of the packages I'm using can be found below:

```json
{
  "name": "curly-potato",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "watch": "webpack --watch"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "thread-loader": "^1.1.0",
    "webpack": "^3.5.5"
  }
}
```

Minimal webpack config:
```js
const path = require('path');

module.exports = {
    entry: path.resolve(__dirname, 'index.js'),
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'index.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                use: [
                    'thread-loader',
                    'babel-loader'
                ]
            }
        ]
    }
};
```

**Comment by sokra** [comment]
fixed
