### ISSUE TITLE
Unit tests never finish if poolTimeout is set to Infinity

### ISSUE THREAD

**Issue by jantimon** [webpack-contrib/thread-loader#50]
I am setting the `poolTimeout` to `Infinity` which prevents my jest runs from tearing down.  

Would it be possible to provide a util function which iterates over all pools and calls `disposeWorkers()`?

**Comment by evilebottnawi** [comment]
@jantimon can you test this https://github.com/webpack-contrib/thread-loader/releases/tag/v2.0.1?

/cc @mistic

**Comment by jantimon** [comment]
Just tested - it is still a problem for my unit tests.  
The reason is that my test runner waits until the child processes finish. (Which will never happen for poolTimeout InfinitY)

**Comment by mistic** [comment]
@jantimon we have detached the child processes from the main one, it's strange it still happening @2.0.1

**Comment by mistic** [comment]
I found a bug @2.0.1 fixed here https://github.com/webpack-contrib/thread-loader/pull/53

It might have fixed your problem here too!

**Comment by jantimon** [comment]
Wow! Very well done works perfectly :)

**Comment by mistic** [comment]
@evilebottnawi you can close this issue now :) it's fixed on 2.0.2
