### ISSUE TITLE
process not closing with thread-loader >=2.0.1

### ISSUE THREAD

**Issue by bdwain** [webpack-contrib/thread-loader#56]
I have an instance of webpack dev server running in a forked process from my main process, and I noticed the fork started sticking around after the main process is closed, when it should be getting closed also. My project uses the thread-loader for babel-loader. The behavior started when I upgraded from thread-loader 2.0.0, and I've narrowed it down to being introduced in 2.0.1, and the only commit in it is #51.

I'm still working on an example I can link to, but basically my code looks like this

```js
//main process
  let child = fork(path.resolve(__dirname, './run-dev-server.js'), params);

  process.on('exit', function(){
    console.log('EXITING')
    child.kill();
  });

//run-dev-server.js

const compiler = webpack(config);
const server = new webpackDevServer(compiler, serverOptions);
server.listen(port, host);

//webpack rule in webpack.config.js
{
  test: /\.js$/,
  exclude: /node_modules|babel-helpers/,
  use: [
    'thread-loader',
    {
       loader: 'babel-loader',
       options: {
         cacheDirectory: true,
         extends: path.join(__dirname, '../.babelrc')
       }
    }
  ]
}
```
when i try to exit the main process, I see that EXITING gets printed, but now the forked process sticks around in the background still running webpack-dev-server. I might be able to change the signal I send to something that can't be ignored, but that seems like something I shouldn't have to do. 

The behavior is not present in v2.0.0 (things work there), but 2.0.1 can reliably reproduce it. I'll try to get something I can link to though.

**Comment by evilebottnawi** [comment]
@bdwain please creare minimum reproducible test repo, thanks

**Comment by kelly-tock** [comment]
same here.

**Comment by mistic** [comment]
@bdwain @kelly-tock I'm digging on the problem

**Comment by mistic** [comment]
A PR is up in order to solve the issue https://github.com/webpack-contrib/thread-loader/pull/57

**Comment by bdwain** [comment]
thank you @mistic !

**Comment by AILINGANGEL** [comment]
I still have this problem, my thread-loader version is '2.1.3' and my npm version is '6.9.0'. Help wanted

**Comment by mistic** [comment]
@AILINGANGEL in order to further investigate this, we need you to provide us a simple repo setup where we can reproduce the problem.

**Comment by meowtec** [comment]
The same problem.  using `ts-loader@6.2.1` + `thread-loader@2.1.3`.

@mistic @evilebottnawi 
Here is my minimum sample:
[thread-loader-bug-reproduce.zip](https://github.com/webpack-contrib/thread-loader/files/3889934/thread-loader-bug-reproduce.zip)

**Comment by JFossey** [comment]
@mistic I am also having the same issue with version **2.1.3** when I use `threadLoader.warmup()`.
