### ISSUE TITLE
Issue with css-loader when passing options with function prop

### ISSUE THREAD

**Issue by ShinyChang** [webpack-contrib/thread-loader#58]
**Environment**

```
OS: Mac OS 10.14
css-loader: 2.1.0
thread-loader: 2.1.2
webpack: 4.28.4
```

**Description**
The `getLocalIdent` which is a custom function in the option of css-loader. It appear in the thread-loader option but not in the css-loader option. As below image shows:
![image](https://user-images.githubusercontent.com/1590707/52030560-66e04d80-2553-11e9-9eba-b3201be4ce47.png)

loader configuration:
```
    'cache-loader',
    {
      loader: 'thread-loader',
      options: workerPool
    },
    {
      loader: 'css-loader',
      options: {
        context: path.resolve(__dirname, '..', '..', 'src'),
        modules: true,
        exportOnlyLocals,
        localIdentName: '[path]__[name]__[local]',
        getLocalIdent: (context, localIdentName, localName) => genLocalIdent(localName, context.resourcePath),
        importLoaders: 2
      }
    },
    'postcss-loader',
    {
      loader: 'sass-loader',
      options: {
        outputStyle: 'expanded',
        includePaths: [
          path.resolve(__dirname, '..', '..', 'src/component-library/_styles'),
          path.resolve(__dirname, '..', '..', 'src/css')
        ]
      }
    }
```

It works fine without thread-loader, so I think this should be thread-loader issue.

Please checkout [sample repo](https://github.com/ShinyChang/webpack-thread-loader-repo) and test it

**Comment by sokra** [comment]
This can't be fixed by design. Closures are not transferrable cross thread/process.

But you can move the thread-loader after the css-loader to run sass and postcard in parallel.

**Comment by ShinyChang** [comment]
Thanks for your reply. I will adjust the order of loaders.

**Comment by DemonCloud** [comment]
@sokra Thanks very much , the bug when use (thread-loader|cache-loader) with css-loader togather, It will ignore css-loader options as ``getLocalIdent ``
