### ISSUE TITLE
.sourceMap is an alias for .sourceMaps, cannot use both from thread-loader

### ISSUE THREAD

**Issue by revurirams123** [webpack-contrib/thread-loader#59]
Hi I am wondering if the below is from thread-loader, do please let me know what I can do to fix this

I have upgraded babel to below versions in reactjs application. 
"babel-core": "7.0.0-bridge.0", 
"@babel/core": "^7.2.2", 
"@babel/polyfill": "^7.2.5", 
"@babel/preset-env": "^7.3.1", 
"@babel/preset-react": "^7.0.0",

After this my webpack build is failing with below error

**ERROR in ./src/App.tsx Module build failed (from ./node_modules/thread-loader/dist/cjs.js): Thread Loader (Worker 0) .sourceMap is an alias for .sourceMaps, cannot use both**

I am not sure where to remove sourceMap/s, i am not using any sourcemap in babel.config.js and I have removed devtool from webpack.config.js Can you please help?

**Comment by mistic** [comment]
@revurirams123 can you create a minimal separate repo which can reproduce the problem?

**Comment by mistic** [comment]
@revurirams123 I just found this is not a problem with the thread-loader but with babel-loader https://github.com/babel/babel-loader/issues/658

You should change the option you have set from using `sourceMap` to `sourceMaps`

**Comment by revurirams123** [comment]
Thank you so much for responding, can you please help a bit here, I am not
using sourceMap in my babel.config.js however i have used it in
webpack.config.js for devtool and for loaders like css-loader, sass-loader
..etc , can you please help how to fix this .thanks so much again.
My babel.config.js is as below:

[image: image.png]
And my webpack.config.js (splitted into two screenshots) is as below
[image: image.png]
[image: image.png]
*Regards,*
*Rama Krishna Revuri*

**Comment by mistic** [comment]
@revurirams123 I really need an example repo in order to be more useful

**Comment by revurirams123** [comment]
Thank you so much for responding, i am afraid that it might not work since
i am dependent on internal libraries, those dependencies will not be
downloaded outside my company, can you please take look into provided
snapshots (in below email) and what is wrong with given babel.config.js or
webpack.config.js,

I tired to change source-map to source-maps for devtool in
webpack.config.js but it is throwing same error, it apparently clear that
babel-loader is reading sourceMap (instead of sourceMaps) from somewhere
which i do not know. please help .
*Regards,*
*Rama Krishna Revuri*

**Comment by mistic** [comment]
I'm not really able to help you without an example repo where you can reproduce the error. Can you try to build an example repo only with the babel configs you have and the webpack config you are using? Otherwise try to search for `sourceMap` and `sourceMaps` and just use always one of the options.

**Comment by revurirams123** [comment]
Thank you for replying, i am not using both in babel.config.js, but i used
source-map for devtool in webpack-config.js, please look at the snapshot of
my babel.config.js file below and I further debugged and put extra logging
in node_modules/@babel/core/lib/config/validation, that log message shows
me that presets in options has both sourceMap and sourceMaps as you see
below screenshot, that is what is creating problem. can you please let me
know if you are aware how to remove sourceMap form presets.
[image: image.png]
[image: image.png]

My babel.config.js :
[image: image.png]

**Comment by mistic** [comment]
Without an example repository reproducing the error to play with, I can't really help too much. Try to upgrade your babel packages (including preset) and babel plugins to the lastest version available.

**Comment by revurirams123** [comment]
Hi @mistic after spending so much time, came to know that this extra sourceMap is coming from dependent library which is not yet ported to babel7. I would like to close this issue, thanks so much for analyzing and for your time.
