### ISSUE TITLE
Error using val-loader

### ISSUE THREAD

**Issue by ElMassimo** [webpack-contrib/thread-loader#68]
Using `thread-loader@2.1.2` which is included through `@vue/cli-service@3.8.4`.

When using `val-loader@1.1.1` in the project, the following error occurs: 

<details>
<summary>Error trace</summary>
<pre>
ERROR in ./app/javascript/evolve/IconAliases.js
Module build failed (from ./node_modules/@vue/cli-service/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'context' of undefined
    at PoolWorker.fromErrorObj (node_modules/@vue/cli-service/node_modules/thread-loader/dist/WorkerPool.js:258:12)
    at Object.exec (node_modules/@vue/cli-service/node_modules/thread-loader/dist/worker.js:155:70)
    at Object.valLoader (node_modules/val-loader/dist/index.js:53:22)
</pre>
</details>

After looking at the source code, I found that the distribution of `2.1.2` has the [following code](https://github.com/webpack-contrib/thread-loader/blob/master/src/worker.js#L137):

```js
exec: (code, filename) => {
  const module = new _module2.default(filename, undefined);
  module.paths = _module2.default._nodeModulePaths(undefined.context); // eslint-disable-line no-underscore-dangle
```
which has `undefined.context` instead of `this.context`.

Thoughts on how to fix it? Also, any workaround to avoid hitting this line?

**Comment by ElMassimo** [comment]
Found a workaround, which is to use `post` in the `val-loader` rule, which ensures it gets executed after the `thread-loader` and `babel-loader` rule.

That said, having `undefined.context` in the released code still seems like a bug, any code that hits that codepath would get an error.

**Comment by max-arias** [comment]
@ElMassimo Got an example? Running into the same issue here.

**Comment by ElMassimo** [comment]
Using [`webpack-chain`](https://github.com/neutrinojs/webpack-chain):

```js
  webpackConfig.module
    .rule('icon')
      .post() // <<< This is what I mentioned in the comment above.
      .test(/.eval.js$/)
      .use('val-loader')
        .loader('val-loader')
```

The generated rule looks like this:

```js
      {
        enforce: 'post',
        test: /.eval.js$/,
        use: [
          {
            loader: 'val-loader'
          }
        ]
      }
```
