### ISSUE TITLE
error when using with 'awesome-typescript-loader'

### ISSUE THREAD

**Issue by xgz123** [webpack-contrib/thread-loader#7]
1.  version: 1.1.1  awesome-typescript-loader: 3.2.3

2. error: ` TypeError: Cannot read property 'parentCompilation' of undefined`

**Comment by johnnyreilly** [comment]
I don't think atl supports thread-loader. You could try using ts-loader (I'm one of the maintainers of it) in `happyPackMode`. (Happypack / thread-loader work in roughly the same way - the name of the option indicates that happypack was there first!) 

You can see an example setup here: https://github.com/TypeStrong/ts-loader/tree/master/examples/thread-loader

Oh and it's advisable to combine thread-loader usage with cache-loader. Hope that helps 🌻

**Comment by johnnyreilly** [comment]
Oh - if you do use ts-loader, ensure you also use the fork-ts-checker-webpack-plugin (used in the example). Without the plugin you'll have no type checking.

**Comment by xgz123** [comment]
@johnnyreilly Thanks, I will try your advice

**Comment by xgz123** [comment]
There was a moment I thought I solved this problem (use atl) and it is really fast(3.5s to 2s).I want  to use atl so I also tried happypack and it works. But about the performance I think thread-loader is better.I hope atl and thread-loader will work together on day.

**Comment by johnnyreilly** [comment]
I'm surprised it would work with happypack but not thread-loader. Funny...

**Comment by xgz123** [comment]
I was wrong ..there are errors in the bundled files (happypack).

**Comment by johnnyreilly** [comment]
Ah - that makes sense.  You can probably get an understanding of why by reading this post: https://medium.com/webpack/typescript-webpack-super-pursuit-mode-83cc568dea79
(maybe that's how you came to try this out in the first place?)

Essentially, using happypack / thread-loader means that some of the webpack APIs tat ts-loader (and I suspect atl) have relied upon.   These need to be worked around in the loader itself.

**Comment by xgz123** [comment]
no-threadloader: around 13s
use threadloader: 9-12s
use ftcwp: around 12s

I think I will use ts-loader and thread-loader for now. nice work

**Comment by johnnyreilly** [comment]
It's worth experimenting with the number of threads you use to get the optimal setup for yourself.  Good luck!
