### ISSUE TITLE
Issue with `sass-loader` (this.getResolve is not a function)

### ISSUE THREAD

**Issue by ngryman** [webpack-contrib/thread-loader#79]
Hey folks,

I've facing the following issue with `sass-loader`:
<details>
<summary><b>Error Details</b></summary><br>

```sh
ERROR in ./app.scss (./node_modules/thread-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./app.scss)
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
this.getResolve is not a function
    at PoolWorker.fromErrorObj (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at mapSeries (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at readBuffer (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/thread-loader/dist/WorkerPool.js:152:14)
    at Object.loader (/Users/ngryman/Projects/Open Source/Code/thread-sass-loaders-bug/node_modules/sass-loader/dist/index.js:52:26)
 @ ./app.scss 1:14-155
```

</details>

When I remove `thread-loader` from the loaders chain, it works correctly. Here is a very simple repo to reproduce that issue: https://github.com/ngryman/thread-sass-loaders-bug.

I've also already surfaced that issue in the `sass-loader` repo as I'm not sure which package is buggy.

**Comment by evilebottnawi** [comment]
Yes, feel free to send a PR

**Comment by evilebottnawi** [comment]
Should be very easy to fix

**Comment by ngryman** [comment]
@evilebottnawi I'd be glad to open a PR but unfortunately I'm not very familiar with `thread-loader` or Webpack's internals. Could you provide me with some help so I can open that PR? Thanks.

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/thread-loader/blob/master/src/index.js#L23 just add `getResolver: this.getResolver` should be work

**Comment by rainke** [comment]
I use MiniCssExtractPlugin.loader still has the error

**Comment by rainke** [comment]
should add `getResolve` in here
https://github.com/webpack-contrib/thread-loader/blob/master/src/worker.js#L120

**Comment by Lsnsh** [comment]
Encountered the same problem, maybe you can look at this issue:
https://github.com/webpack-contrib/sass-loader/issues/761#issuecomment-554608680

**Comment by ryansully** [comment]
The same error occurs for [less-loader 6.0.0](https://github.com/webpack-contrib/less-loader/releases/tag/v6.0.0).
