### ISSUE TITLE
How to use thread-loader in vue-cli3?

### ISSUE THREAD

**Issue by Mrdouhua** [webpack-contrib/thread-loader#97]
1. version: 2.1.3
2. My method is config.module.rule('vue').use('thread-loader')
![image](https://user-images.githubusercontent.com/17821353/91423340-00382880-e88b-11ea-939c-56836baa8951.png)

3. Here is a screenshot of the console error
![image](https://user-images.githubusercontent.com/17821353/91423579-4f7e5900-e88b-11ea-9326-baf5aa62b2f1.png)

**Comment by evilebottnawi** [comment]
Please ask this question in `vue-cli3` repo
